# Generated by Django 5.0.6 on 2024-06-23 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('graph_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='edge',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='vertex',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
