# Generated by Django 5.0.6 on 2024-06-11 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('graph_api', '0002_edge_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vertex',
            name='name',
        ),
        migrations.AlterField(
            model_name='edge',
            name='id',
            field=models.CharField(max_length=50, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='vertex',
            name='id',
            field=models.CharField(max_length=50, primary_key=True, serialize=False),
        ),
    ]
