# Generated by Django 5.0.6 on 2024-06-11 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('graph_api', '0003_remove_vertex_name_alter_edge_id_alter_vertex_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='edge',
            name='id',
            field=models.CharField(max_length=150, primary_key=True, serialize=False),
        ),
    ]
