# Generated by Django 5.0.6 on 2024-06-11 15:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('graph_api', '0004_alter_edge_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vertex',
            old_name='id',
            new_name='name',
        ),
    ]
