# Generated by Django 5.0.6 on 2024-06-11 15:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('graph_api', '0005_rename_id_vertex_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='edge',
            old_name='id',
            new_name='name',
        ),
    ]
