# Generated by Django 5.0.6 on 2024-06-11 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('graph_api', '0006_rename_id_edge_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='edge',
            name='description',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
