# Generated by Django 5.0.6 on 2024-06-11 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('graph_api', '0007_alter_edge_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='edge',
            name='name',
            field=models.CharField(blank=True, max_length=150, primary_key=True, serialize=False),
        ),
    ]
